# Generated by Django 2.0.5 on 2018-05-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180508_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
