# Generated by Django 2.0.5 on 2018-09-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180513_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_bought',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
