# Generated by Django 2.0.5 on 2018-09-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180513_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slack_handle',
            field=models.CharField(default=None, help_text='Without @-char. Leave empty to disable notifications', max_length=50, null=True),
        ),
    ]
