# Generated by Django 2.0.5 on 2018-09-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180917_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_bought',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slack_handle',
            field=models.CharField(blank=True, default=None, help_text='Without @-char. Leave empty to disable notifications', max_length=50, null=True),
        ),
    ]
