jobs:
  include:
    - stage: test
      language: python
      python:
        - 3.6
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
        - cp sahkopiikki/settings.template.py sahkopiikki/settings.py
      script:
        - python manage.py test
    - stage: test
      language: node_js
      node_js:
        - '10'
      before_install:
        - cd frontend
      install:
        - npm ci
        - npm run build
      script:
        - npm run test
    - stage: deploy
      if: branch = production
      language: node_js
      node_js:
        - '10'
      before_script:
        - openssl aes-256-cbc -K $encrypted_19f1f1d7001a_key -iv $encrypted_19f1f1d7001a_iv -in deploy/deploy_key.enc -out deploy/deploy_key -d
      script: bash deploy/deploy.sh

notifications:
  email: false
  slack: radiodiodi:bKmg9JXX91Ijut1X6dy5zcK1