language: node_js
node_js:
  - '8'
install:
  - pushd frontend
  - npm ci
  - popd
script:
  - pushd frontend
  - cp .env.template .env
  - npm run build
  - npm run test
  - popd
before_deploy:
  - openssl aes-256-cbc -K $encrypted_19f1f1d7001a_key -iv $encrypted_19f1f1d7001a_iv -in deploy_key.enc -out /tmp/deploy_key -d
deploy:
  provider: script
  script: bash .travis_deploy.sh
  on:
    branch: production
